name: Build TypeScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Updated to Node.js 18 (or 20 if you prefer)

    - name: Install dependencies
      run: |
        npm install

    - name: Compile TypeScript
      run: |
        npm run build

    - name: Upload compiled files to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: compiled-files
        path: ./dist  # Ensure that your tsconfig.json outputs compiled files here
